
import javax.swing.JOptionPane;


public class Form_Laundry extends javax.swing.JFrame {

    public Form_Laundry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Jenis = new javax.swing.JComboBox<>();
        Bayar = new javax.swing.JTextField();
        Harga = new javax.swing.JTextField();
        Berat = new javax.swing.JTextField();
        Ttl_Harga = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Laundry Putih Berseri");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 280, 50));

        jLabel2.setFont(new java.awt.Font("High Tower Text", 1, 14)); // NOI18N
        jLabel2.setText("Jumlah Bayar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 100, 30));

        jLabel3.setFont(new java.awt.Font("High Tower Text", 1, 14)); // NOI18N
        jLabel3.setText("Jenis Cucian ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 100, 30));

        jLabel4.setFont(new java.awt.Font("High Tower Text", 1, 14)); // NOI18N
        jLabel4.setText("Harga Cucian @kilo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 150, 30));

        jLabel5.setFont(new java.awt.Font("High Tower Text", 1, 14)); // NOI18N
        jLabel5.setText("Berat Cucian");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 100, 30));

        jLabel6.setFont(new java.awt.Font("High Tower Text", 1, 14)); // NOI18N
        jLabel6.setText("Total Harga Cucian");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 150, 30));

        Jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Cuci Kering", "Cuci Basah", "Cuci Setrika" }));
        Jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JenisActionPerformed(evt);
            }
        });
        jPanel1.add(Jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 150, -1));

        Bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarActionPerformed(evt);
            }
        });
        jPanel1.add(Bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 150, 30));

        Harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaActionPerformed(evt);
            }
        });
        jPanel1.add(Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 150, 30));

        Berat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeratActionPerformed(evt);
            }
        });
        Berat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BeratKeyReleased(evt);
            }
        });
        jPanel1.add(Berat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 150, 30));

        Ttl_Harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ttl_HargaActionPerformed(evt);
            }
        });
        jPanel1.add(Ttl_Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 150, 30));

        jButton1.setText("Transaksi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        jButton2.setText("Batalkan Pesanan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 490);

        setSize(new java.awt.Dimension(423, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeratActionPerformed

    }//GEN-LAST:event_BeratActionPerformed

    private void BayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BayarActionPerformed

    private void JenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JenisActionPerformed
        if(Jenis.getSelectedItem().toString().equalsIgnoreCase("Cuci Kering")){
            Harga.setText("4500");
        }else if (Jenis.getSelectedItem().toString().equalsIgnoreCase("Cuci Basah")){
            Harga.setText("3500");
        }else if (Jenis.getSelectedItem().toString().equalsIgnoreCase("Cuci Setrika")){
            Harga.setText("5500");
        }
    }//GEN-LAST:event_JenisActionPerformed

    private void HargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int bayar = Integer.parseInt(Bayar.getText());
        int ttl_harga = Integer.parseInt(Ttl_Harga.getText());
        double kembalian = bayar - ttl_harga;
        String kembali = Double.toString(kembalian);
        JOptionPane.showMessageDialog(null,"Kembalian Anda : n" + kembali);
        
        Jenis.setSelectedItem("pilih");
        Harga.setText("");
        Berat.setText("");
        Ttl_Harga.setText("");
        Bayar.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Jenis.setSelectedItem("pilih");
        Harga.setText("");
        Berat.setText("");
        Ttl_Harga.setText("");
        Bayar.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Ttl_HargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ttl_HargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ttl_HargaActionPerformed

    private void BeratKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BeratKeyReleased
        int harga = Integer.parseInt(Harga.getText());
        int berat = Integer.parseInt(Berat.getText());
        double total_bayar = harga * berat;
        String total = Double.toString(total_bayar);
        Ttl_Harga.setText(total);
    }//GEN-LAST:event_BeratKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Laundry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bayar;
    private javax.swing.JTextField Berat;
    private javax.swing.JTextField Harga;
    private javax.swing.JComboBox<String> Jenis;
    private javax.swing.JTextField Ttl_Harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
